"""Update order datetimes

Revision ID: 674e5cdf1c7b
Revises: 15b03bf4ed08
Create Date: 2023-01-16 18:26:12.955019

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "674e5cdf1c7b"
down_revision = "15b03bf4ed08"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
