version: "3.9"
services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_URL: db
      POSTGRES_DB_NAME: app_db
      POSTGRES_PORT: 5432
      JWT_SECRET: secret
    healthcheck:
      test: ["CMD-SHELL", " netstat -an | grep 0.0.0.0:80" ]
      interval: 10s
      timeout: 5s
      retries: 2
#    command: /bin/sh -c "./startupFinalisation.sh"
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    stdin_open: true
    ports:
      - "8081:8081"
    depends_on:
      app:
        condition: service_healthy
      db:
        condition: service_started
  db:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
volumes:
  pgdata:
    driver: local
